baseURL = 'https://tisicstry.top/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "book"

[params]
  # (Optional, default docs) Specify root page to render child pages as menu.
  # Set '*' to render all sections to menu.
  BookSection = '*'
  
  # (Optional) Set true to enable search
  BookSearch = true
  
  # Set theme to light by default to match your CSS logic if applicable
  BookTheme = 'light'
